<!doctype html>
<html lang="en">
    <head>
        <title><?=$this->title;?></title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <style>
            a.list-group-item[data-bs-toggle="collapse"]:after {
                position: relative; top: 0.15em;
                content: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2216%22%20height%3D%2216%22%20fill%3D%22currentColor%22%20class%3D%22bi%20bi-chevron-right%22%20viewBox%3D%220%200%2016%2016%22%3E%3Cpath%20fill-rule%3D%22evenodd%22%20d%3D%22M4.646%201.646a.5.5%200%200%201%20.708%200l6%206a.5.5%200%200%201%200%20.708l-6%206a.5.5%200%200%201-.708-.708L10.293%208%204.646%202.354a.5.5%200%200%201%200-.708z%22%2F%3E%3C%2Fsvg%3E");
                float: right;
                transition: transform .35s ease;
            }

            a.list-group-item[data-bs-toggle="collapse"][aria-expanded="true"]:after {
                transform: rotate(90deg);
            }

            main > .list-group .list-group a.list-group-item {
                background: #fafafa;
            }
        </style>
    </head>
    <body>
        <header class="navbar navbar-light bg-light mb-4">
            <div class="container">
                <a class="navbar-brand" href="#">Тестовое задание для Webbooster</a>
            </div>
        </header>

        <main class="container">
            <?php foreach($this->catalog as $catalog): ?>
                <?php $this->render('Partial/CatalogWrap', ['catalog' => $catalog]); ?>
            <?php endforeach; ?>
        </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>